# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'What2Do' do
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'Timepiece'
end

target 'What2DoTests' do

end

target 'What2DoUITests' do

end

