# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=65)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('api_class', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('required', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.App')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('beacon_uuid', models.CharField(max_length=200)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.App')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beacon_major', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('beacon_minor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.Service')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.AppConfig')),
            ],
        ),
    ]
