# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceparams',
            old_name='Service',
            new_name='service',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='campaign',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='beacon_uuid',
            field=models.CharField(max_length=200, verbose_name='Beacon UUID'),
        ),
    ]
